'use strict';

/**
 * Receipt schema definition.
 * A receipt is generated by an organization.
 * A organization has no of stores. Each store has an id
 *
 * @author      ritesh
 * @version     1.0
 */

var mongoose = require('../datasource').getMongoose(),
  Schema = mongoose.Schema;

var ReceiptSchema = new Schema({
  orgId: { type: String, required: true },
  staff: { type: String, required: true },
  storeId: { type: String, required: true },
  amount: { type: Number, required: true },
  type: { type: String, required: true, enum: ['purchase', 'return'] },
  userId: { type: String, required: true },
  items: { type: Schema.Types.Mixed, required: true }
});

/**
 * Module exports
 */
module.exports = {
  ReceiptSchema: ReceiptSchema
};